# Site settings
title: Kgzhang Blog
SEOTitle: 张召的博客 | Kgzhang Blog
header-img: img/home-bg.jpg
email:
description: "关于程序与设计、黑客与画家 | 张召，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Kougazhang张召 的个人博客，与你一起发现更大的世界。"
keyword: "张召, Kougazhang张召, Kougazhang, 鬼栈, Kougazhangpro, @Kougazhangpro, 张召的博客, Kougazhang Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
wechat:  img/wechat.jpeg # wechat picture
zhihu_username:     kougazhang
github_username:    kougazhang
#twitter_username:   Kougazhangpro
#facebook_username:  Kougazhangpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username:

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-G8NG8E6SGC'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "张召，前端娱乐圈，Gopher/BigData"
sidebar-avatar: /img/avatar-kougazhang.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
{
  title: "html_table_2_markdown",
  href: "https://kougazhang.github.io/table2markdown"
},
{
  title: "pretty-json",
  href: "https://kougazhang.github.io/pretty-json"
}
]

repositories: [
{
  title: "BigData",
  href: "https://kougazhang.github.io/2021/05/28/bigdata/"
},
{
  title: "Frontend",
  href: "https://kougazhang.github.io/2021/05/28/frontend/"
},
{
  title: "Golang",
  href: "https://kougazhang.github.io/2021/05/28/golang/"
},
{
  title: "Linux",
  href: "https://kougazhang.github.io/2021/06/04/linux/"
},
{
  title: "Booklist",
  href: "https://kougazhang.github.io/2021/07/06/booklist/"
}
]